# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Connor Duffin
email: cpd32@cam.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Postdoc, CSML group, Cambridge University
baseurl: ""
url: ""
github_username:  connor-duffin
twitter_username: cpduffin

# github_username: # your GitHub user name
# gitlab_username: # your GitLab user name
# twitter_username: # your Twitter handle
# linkedin_username: # your LinkedIn user name
# scholar_userid: # your Google Scholar ID
# semanticscholar_id: # your Semantic Scholar ID
# orcid_id: # your ORCID ID
# medium_username: # your Medium username
# quora_username: # your Quora username
# publons_id: # your ID on Publons
# research_gate_profile: # your profile on ResearchGate
# blogger_url: # your blogger URL
# work_url: # work page URL
# keybase_username: # your keybase user name
# wikidata_id: # your wikidata id
# dblp_url: # your DBLP profile url
# stackoverflow_id: # your stackoverflow id
# kaggle_id: # your kaggle id
# lastfm_id: # your lastfm id
# spotify_id: # your spotify id
# pinterest_id: # your pinterest id
# unsplash_id: # your unsplash id
# instagram_id: # your instagram id
# facebook_id: # your facebook id
# discord_id: # your discord id (18-digit unique numerical identifier)

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
